version: '3.6'
services:
  foods:
    image: webdevops/php-apache-dev:8.0
    working_dir: /var/www
    environment: ['WEB_DOCUMENT_ROOT=/var/www/public', 'DOCUMENT_ROOT=/var/www/public/', 'WEB_DOCUMENT_INDEX=/var/www/public/index.php', 'PHP_IDE_CONFIG=serverName=mongotest', 'PHP_DEBUGGER=xdebug', 'XDEBUG_MODE=debug', 'XDEBUG_START_WITH_REQUEST=yes','XDEBUG_CLIENT_HOST=host.docker.internal', 'PM_MAX_REQUESTS=500', 'PHP_MEMORY_LIMIT=2G']
    container_name: mongotest
    shm_size: 2g
    volumes:
      - .:/var/www
    ports:
      - '8086:80'
    networks:
      - mongotest

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
    networks:
      - mongotest

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://root:test@mongo:27017/
    networks:
      - mongotest

networks:
  mongotest:
    external: true
